### ISSUE TITLE
没有移动端

### ISSUE THREAD

**Issue by funet8** [zyx0814/Pichome#2]
1.没有移动端的模板页面？
2.不支持HTTPS，怎么解决？

Dzz! Mobile System Error
Error messages:
模版文件未找到或者无法访问: /mobile/page/index.htm, mobile/page/index.htm

**Comment by zyx0814** [comment]
1.移动端会在下个版本更新。
2.HTTPS是支持的。如有问题可以加QQ群：778791275 交流
