### ISSUE TITLE
上传的视频无法显示缩略图，imageMagick。ffmpeg。都已开启

### ISSUE THREAD

**Issue by duof** [zyx0814/Pichome#36]
如题

**Comment by duof** [comment]
![Uploading Snipaste_2024-08-06_13-35-25.png…]()

**Comment by duof** [comment]
单独上传封面显示正常，更新自动的 显示空白 地址为：/index.php?mod=io&op=getImg&path=SVFxVDdjX1owS0VqSkJuajl2VHdTTEZlWWprSEtGTXpxdHJaMTl5eGJBQ2RqQ1FZelNWREdSYXdGNTN4VnEzRktMMTBWUWFy

**Comment by cyphper** [comment]
> 单独上传封面显示正常，更新自动的 显示空白 地址为：/index.php?mod=io&op=getImg&path=SVFxVDdjX1owS0VqSkJuajl2VHdTTEZlWWprSEtGTXpxdHJaMTl5eGJBQ2RqQ1FZelNWREdSYXdGNTN4VnEzRktMMTBWUWFy

这个ffmpeg需要在存储位置开启，才能真正生效，而不是去修改数据库。这里得开启是有条件依赖判断的，linux下注意需要去掉proc_open函数的禁用，和对应ffmpeg的web执行权限，否则设置里面开启不了。
